export enum DS_IconsEnum {
    filter = 'icon-filter',
    chevronTop = 'icon-chevron-top',
    chevronBottom = 'icon-chevron-bottom',
    chevronLeft = 'icon-chevron-left',
    chevronRight = 'icon-chevron-right',
    arrowTop = 'icon-arrow-top',
    arrowDown = 'icon-arrow-bottom',
    arrowLeft = 'icon-arrow-left',
    arrowRight = 'icon-arrow-right',
    check = 'icon-check',
    search = 'icon-search',
    cross = 'icon-cross',
    plus = 'icon-plus',
    user = 'icon-user',
    calendar = 'icon-calendar',
    table = 'icon-table',
    draggable = 'icon-draggable',
    pin = 'icon-pin',
    unpin = 'icon-unpin',
    home = 'icon-home'
}
