import { BridgesNameEnum } from './../../enums/bridge-name.enum';
import { BuildingNameEnum } from './../../enums/building-name.enum';
import { Pointer } from "../models/pointer.model"

export const RSNM: Pointer = {
    name: BuildingNameEnum.RSNM,
    description: '',
    distanceToReverseClockwise: {
        [BuildingNameEnum.RSNM]: 0,
        [BuildingNameEnum.UNL]: 500,
        [BuildingNameEnum.CONFLUENT]: 650,
        [BuildingNameEnum.MAMAC]: 1140,
        [BuildingNameEnum.MEDIACITE]: 1650,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: 0,
        [BridgesNameEnum.PONT_FRAGNE]: 880,
        [BridgesNameEnum.PONT_CHEMIN_FER]: 1300,
        [BridgesNameEnum.PONT_LIEGE]: 1400,
        [BridgesNameEnum.PONT_FETINNE]: 880,
        [BridgesNameEnum.PONT_NAMUR]: 1260,
        [BridgesNameEnum.PONT_BELLE_ILE]: 1710,
        [BridgesNameEnum.PONT_MATIVA]: 850,
        [BridgesNameEnum.PONT_PARC]: 1360,
        [BridgesNameEnum.PONT_HUY]: 1750,
        [BridgesNameEnum.PONT_LONGDOZ]: 2230,
        [BridgesNameEnum.PONT_AMERCOEUR]: 2840,
        [BridgesNameEnum.PONT_BRESSOUX]: 3380,
        [BridgesNameEnum.PONT_ARCHE]: 6350,
        [BridgesNameEnum.PONT_SAUCY]: 6600,
        [BridgesNameEnum.PONT_JF_KENNEDY]: 7000,
        [BridgesNameEnum.PONT_ALBERT_1]: 7600
    },
    distanceToClockwise: {
        [BuildingNameEnum.RSNM]: 0,
        [BuildingNameEnum.CONFLUENT]: 7450,
        [BuildingNameEnum.UNL]: 7600,
        [BuildingNameEnum.MAMAC]: 6960,
        [BuildingNameEnum.MEDIACITE]: 6450,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: 0,
        [BridgesNameEnum.PONT_FRAGNE]: 7650,
        [BridgesNameEnum.PONT_CHEMIN_FER]: 8120,
        [BridgesNameEnum.PONT_LIEGE]: 8220,
        [BridgesNameEnum.PONT_FETINNE]: 7660,
        [BridgesNameEnum.PONT_NAMUR]: 8000,
        [BridgesNameEnum.PONT_BELLE_ILE]: 8500,
        [BridgesNameEnum.PONT_MATIVA]: 7250,
        [BridgesNameEnum.PONT_PARC]: 6740,
        [BridgesNameEnum.PONT_HUY]: 6350,
        [BridgesNameEnum.PONT_LONGDOZ]: 5870,
        [BridgesNameEnum.PONT_AMERCOEUR]: 5260,
        [BridgesNameEnum.PONT_BRESSOUX]: 4720,
        [BridgesNameEnum.PONT_ARCHE]: 1750,
        [BridgesNameEnum.PONT_SAUCY]: 1500,
        [BridgesNameEnum.PONT_JF_KENNEDY]: 1100,
        [BridgesNameEnum.PONT_ALBERT_1]: 500
    }
};

export const MEDIACITE: Pointer = {
    name: BuildingNameEnum.MEDIACITE,
    description: '',
    distanceToReverseClockwise: {
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 6450,
        [BuildingNameEnum.UNL]: 0,
        [BuildingNameEnum.CONFLUENT]: 0,
        [BuildingNameEnum.MAMAC]: 0,
        [BridgesNameEnum.PONT_HUY]: 0,
        [BridgesNameEnum.PONT_LONGDOZ]: 0,
        [BridgesNameEnum.PONT_AMERCOEUR]: 0,
        [BridgesNameEnum.PONT_BRESSOUX]: 0,
        [BridgesNameEnum.PONT_ARCHE]: 0,
        [BridgesNameEnum.PONT_SAUCY]: 0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: 0,
        [BridgesNameEnum.PONT_ALBERT_1]: 0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: 0,
        [BridgesNameEnum.PONT_FRAGNE]: 0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: 0,
        [BridgesNameEnum.PONT_LIEGE]: 0,
        [BridgesNameEnum.PONT_FETINNE]: 0,
        [BridgesNameEnum.PONT_NAMUR]: 0,
        [BridgesNameEnum.PONT_BELLE_ILE]: 0,
        [BridgesNameEnum.PONT_MATIVA]: 0,
        [BridgesNameEnum.PONT_PARC]: 0,
    },
    distanceToClockwise: {
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1650,
        [BuildingNameEnum.UNL]: 0,
        [BuildingNameEnum.CONFLUENT]: 0,
        [BuildingNameEnum.MAMAC]: 0,
        [BridgesNameEnum.PONT_HUY]: 0,
        [BridgesNameEnum.PONT_LONGDOZ]: 0,
        [BridgesNameEnum.PONT_AMERCOEUR]: 0,
        [BridgesNameEnum.PONT_BRESSOUX]: 0,
        [BridgesNameEnum.PONT_ARCHE]: 0,
        [BridgesNameEnum.PONT_SAUCY]: 0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: 0,
        [BridgesNameEnum.PONT_ALBERT_1]: 0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: 0,
        [BridgesNameEnum.PONT_FRAGNE]: 0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: 0,
        [BridgesNameEnum.PONT_LIEGE]: 0,
        [BridgesNameEnum.PONT_FETINNE]: 0,
        [BridgesNameEnum.PONT_NAMUR]: 0,
        [BridgesNameEnum.PONT_BELLE_ILE]: 0,
        [BridgesNameEnum.PONT_MATIVA]: 0,
        [BridgesNameEnum.PONT_PARC]: 0,
    }

};

export const UNL: Pointer = {
    name: BuildingNameEnum.UNL,
    description: '',
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: 0,
        [BuildingNameEnum.CONFLUENT]: 0,
        [BuildingNameEnum.MAMAC]: 0,
        [BuildingNameEnum.MEDIACITE]: 0,
        [BuildingNameEnum.RSNM]: 7600,
        [BridgesNameEnum.PONT_MATIVA]: 0,
        [BridgesNameEnum.PONT_PARC]: 0,
        [BridgesNameEnum.PONT_HUY]: 0,
        [BridgesNameEnum.PONT_LONGDOZ]: 0,
        [BridgesNameEnum.PONT_AMERCOEUR]: 0,
        [BridgesNameEnum.PONT_BRESSOUX]: 0,
        [BridgesNameEnum.PONT_ARCHE]: 0,
        [BridgesNameEnum.PONT_SAUCY]: 0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: 0,
        [BridgesNameEnum.PONT_ALBERT_1]: 0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: 0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
    },
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: 0,
        [BuildingNameEnum.CONFLUENT]: 0,
        [BuildingNameEnum.MAMAC]: 0,
        [BuildingNameEnum.MEDIACITE]: 0,
        [BuildingNameEnum.RSNM]: 500,
        [BridgesNameEnum.PONT_MATIVA]: 0,
        [BridgesNameEnum.PONT_PARC]: 0,
        [BridgesNameEnum.PONT_HUY]: 0,
        [BridgesNameEnum.PONT_LONGDOZ]: 0,
        [BridgesNameEnum.PONT_AMERCOEUR]: 0,
        [BridgesNameEnum.PONT_BRESSOUX]: 0,
        [BridgesNameEnum.PONT_ARCHE]: 0,
        [BridgesNameEnum.PONT_SAUCY]: 0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: 0,
        [BridgesNameEnum.PONT_ALBERT_1]: 0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: 0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
    }

};

export const MAMAC: Pointer = {
    name: BuildingNameEnum.MAMAC,
    description: '',
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 6960,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1140,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const CONFLUENT: Pointer = {
    name: BuildingNameEnum.CONFLUENT,
    description: '',
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 7450,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 650,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_MATIVA: Pointer = {
    name: BridgesNameEnum.PONT_MATIVA,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 850,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 7250,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_BELLE_LIEGEOISE: Pointer = {
    name: BridgesNameEnum.PONT_BELLE_LIEGEOISE,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 0,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 0,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_ALBERT_1: Pointer = {
    name: BridgesNameEnum.PONT_ALBERT_1,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 7600,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 50,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_PARC: Pointer = {
    name: BridgesNameEnum.PONT_PARC,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1360,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 6740,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_HUY: Pointer = {
    name: BridgesNameEnum.PONT_HUY,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1750,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 6350,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_JF_KENNEDY: Pointer = {
    name: BridgesNameEnum.PONT_JF_KENNEDY,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 7000,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1100,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_LONGDOZ: Pointer = {
    name: BridgesNameEnum.PONT_LONGDOZ,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 2230,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 5870,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_SAUCY: Pointer = {
    name: BridgesNameEnum.PONT_SAUCY,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 6600,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1500,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_ARCHE: Pointer = {
    name: BridgesNameEnum.PONT_ARCHE,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 6350,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1750,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_AMERCOEUR: Pointer = {
    name: BridgesNameEnum.PONT_AMERCOEUR,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 2840,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 5260,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_BRESSOUX: Pointer = {
    name: BridgesNameEnum.PONT_BRESSOUX,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 3380,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 4720,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

/////////// HORS ILE

export const PONT_LIEGE: Pointer = {
    name: BridgesNameEnum.PONT_LIEGE,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1400,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 8220,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_CHEMIN_FER: Pointer = {
    name: BridgesNameEnum.PONT_CHEMIN_FER,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1300,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 8120,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_FRAGNE: Pointer = {
    name: BridgesNameEnum.PONT_FRAGNE,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 880,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 7650,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_BELLE_ILE: Pointer = {
    name: BridgesNameEnum.PONT_BELLE_ILE,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1710,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 8500,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_NAMUR: Pointer = {
    name: BridgesNameEnum.PONT_NAMUR,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 1260,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: 0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 8000,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};

export const PONT_FETINNE: Pointer = {
    name: BridgesNameEnum.PONT_FETINNE,
    description: '',
    distanceToClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 880,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    },
    distanceToReverseClockwise: {
        [BuildingNameEnum.UNL]: -0,
        [BuildingNameEnum.MEDIACITE]: -0,
        [BuildingNameEnum.RSNM]: 7660,
        [BuildingNameEnum.MAMAC]: -0,
        [BuildingNameEnum.CONFLUENT]: -0,
        [BridgesNameEnum.PONT_LIEGE]: -0,
        [BridgesNameEnum.PONT_CHEMIN_FER]: -0,
        [BridgesNameEnum.PONT_FRAGNE]: -0,
        [BridgesNameEnum.PONT_BELLE_ILE]: -0,
        [BridgesNameEnum.PONT_NAMUR]: -0,
        [BridgesNameEnum.PONT_FETINNE]: -0,
        [BridgesNameEnum.PONT_MATIVA]: -0,
        [BridgesNameEnum.PONT_BELLE_LIEGEOISE]: -0,
        [BridgesNameEnum.PONT_ALBERT_1]: -0,
        [BridgesNameEnum.PONT_PARC]: -0,
        [BridgesNameEnum.PONT_HUY]: -0,
        [BridgesNameEnum.PONT_JF_KENNEDY]: -0,
        [BridgesNameEnum.PONT_LONGDOZ]: -0,
        [BridgesNameEnum.PONT_SAUCY]: -0,
        [BridgesNameEnum.PONT_ARCHE]: -0,
        [BridgesNameEnum.PONT_AMERCOEUR]: -0,
        [BridgesNameEnum.PONT_BRESSOUX]: -0
    }

};




export const ISLAND_TOUR = 8100;
export const ALL_POINTERS = [
    RSNM,
    MEDIACITE,
    UNL,
    MAMAC,
    CONFLUENT,
    PONT_LIEGE,
    PONT_CHEMIN_FER,
    PONT_FRAGNE,
    PONT_BELLE_ILE,
    PONT_NAMUR,
    PONT_FETINNE,
    PONT_MATIVA,
    PONT_BELLE_LIEGEOISE,
    PONT_ALBERT_1,
    PONT_PARC,
    PONT_HUY,
    PONT_JF_KENNEDY,
    PONT_LONGDOZ,
    PONT_SAUCY,
    PONT_ARCHE,
    PONT_AMERCOEUR,
    PONT_BRESSOUX
];
